{% set name = "cbgen" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60719737ca40cc69577ed0c58b86a507638f311173ae21ae92fc185cc2b304a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - bgen >=4.1.3
    - cffi >=1.15.1
    - pip
    - python
    - poetry-core >=1.0.8
  run:
    - appdirs >=1.4.3
    - bgen >=4.1.3
    - cffi >=1.14.0
    - numpy >=1.17.0
    - pooch >=1.1.1
    - pytest >=5.4.1
    - python

test:
  requires:
    - pytest
  imports:
    - cbgen
  commands:
    - python -c "import sys; import cbgen; sys.exit(cbgen.test())"

about:
  home: https://github.com/limix/cbgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper around a BGEN library
  description: |
    BGEN is a file format for storing large genetic datasets. It supports both unphased
    genotypes and phased haplotype data with variable ploidy and number of alleles. It
    was designed to provide a compact data representation without sacrificing variant
    access performance. This Python package is a wrapper around the bgen library, a
    low-memory footprint reader that efficiently reads bgen files.
  doc_url: https://cbgen.readthedocs.io/en/stable/
  dev_url: https://github.com/limix/cbgen

extra:
  recipe-maintainers:
    - Horta
